/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Operacao;

/**
 *
 * @author Angel Banze
 */
public class Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClienteNovo
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtApelido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomes = new javax.swing.JTextField();
        txtCell = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnSubmit1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(144, 180, 90));
        jPanel1.setLayout(null);

        txtApelido.setBackground(new java.awt.Color(144, 180, 90));
        txtApelido.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtApelido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtApelido);
        txtApelido.setBounds(210, 100, 130, 20);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Apelido");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 100, 58, 18);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Outros nomes");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 130, 109, 18);

        txtNomes.setBackground(new java.awt.Color(144, 180, 90));
        txtNomes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtNomes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtNomes);
        txtNomes.setBounds(210, 130, 130, 20);

        txtCell.setBackground(new java.awt.Color(144, 180, 90));
        txtCell.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtCell.setText("+258 ");
        txtCell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtCell);
        txtCell.setBounds(210, 160, 131, 20);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Celular");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 160, 54, 18);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("e-mail");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 190, 47, 18);

        txtEmail.setBackground(new java.awt.Color(144, 180, 90));
        txtEmail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtEmail.setText("eg: xxx@hotmail.com ");
        txtEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtEmail);
        txtEmail.setBounds(170, 190, 177, 20);

        jRadioButton2.setBackground(new java.awt.Color(144, 180, 90));
        jRadioButton2.setText("Fem");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(250, 220, 41, 19);

        jRadioButton1.setBackground(new java.awt.Color(144, 180, 90));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Masc");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(190, 220, 45, 19);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Genero");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 220, 56, 18);

        btnSubmit.setBackground(new java.awt.Color(144, 180, 90));
        btnSubmit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Submit.png"))); // NOI18N
        btnSubmit.setText("Submeter");
        btnSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnSubmit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(550, 450, 190, 60);

        btnSubmit1.setBackground(new java.awt.Color(144, 180, 90));
        btnSubmit1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSubmit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Submit.png"))); // NOI18N
        btnSubmit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnSubmit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit1);
        btnSubmit1.setBounds(160, 260, 60, 60);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Codigo");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 70, 55, 18);

        txtCod.setBackground(new java.awt.Color(144, 180, 90));
        txtCod.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtCod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtCod);
        txtCod.setBounds(210, 70, 130, 20);

        btnPesquisa.setBackground(new java.awt.Color(144, 180, 90));
        btnPesquisa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(btnPesquisa);
        btnPesquisa.setBounds(410, 70, 110, 20);

        btnApagar.setBackground(new java.awt.Color(144, 180, 90));
        btnApagar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/X.png"))); // NOI18N
        btnApagar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnApagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnApagar);
        btnApagar.setBounds(240, 261, 60, 59);

        btnUpdate.setBackground(new java.awt.Color(144, 180, 90));
        btnUpdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpdate.setText("Actualizar");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(510, 430, 90, 44);

        btnUpdate1.setBackground(new java.awt.Color(144, 180, 90));
        btnUpdate1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpdate1.setText("Actualizar");
        btnUpdate1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnUpdate1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnUpdate1);
        btnUpdate1.setBounds(320, 260, 90, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmit1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton2.isEnabled()){
            jRadioButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isEnabled()){
            jRadioButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmit1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtCell;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomes;
    // End of variables declaration//GEN-END:variables
}
