/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Operacao;

import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import Validacao.Conexao;

/**
 *
 * @author Angel Banze
 */
public class Fornecimento extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    PreparedStatement pst2 = null;
    ResultSet rs = null;
    /**
     * Creates new form Fornecimento
     */
    public Fornecimento() {
        initComponents();
        conexao = Conexao.Conector();
    }

    private void PesquisaFornecedor(){
        
        String sql = "select * from fornecedor where forn_cod like ?";
        
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtFornCod.getText() + "%");
            rs = pst.executeQuery();
            
            if (rs.next()){
                txtFornCod.setText(rs.getString(1));
                txtFornNome.setText(rs.getString(2));
            } else {
                JOptionPane.showMessageDialog(null, "fornecedor não encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void AdicionarProduto (){
        String sql1 = "insert into produto (prod_nome, prod_validade, prod_preco, nota) Values (?, ?, ?, ?)";
        
        try {
            pst = conexao.prepareStatement(sql1);
            pst.setString(1, txtProduto.getText());
            pst.setString(2, txtValidade.getText());
            pst.setString(3, txtPreco.getText());
            pst.setString(4, txtNota.getText());
            
            if(txtProduto.getText().equals("") || txtValidade.getText().equals("") || txtPreco.getText().equals("") || txtQuantidade.getText().equals("") || txtFornNome.getText().equals("") || txtFornCod.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatorios sff");
            } else{
                pst.executeUpdate();
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        recuperarCod ();
        
        String sql2 = "insert into fornece (cod_forn, cod_prod, quantidade) values (?, ?, ?)";
        
        try {
            pst2 = conexao.prepareStatement(sql2);
            
            pst2.setString(1, txtFornCod.getText());
            pst2.setString(2, txtCod.getText());
            pst2.setString(3, txtQuantidade.getText());
            
            int result = pst2.executeUpdate();
                
                if(result > 0){
                    JOptionPane.showMessageDialog(null, "Produto adicionado com sucesso!!!");
                    
                }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        txtProduto.setText(null);
        txtValidade.setText(null);
        txtPreco.setText(null);
        txtNota.setText(null);
        txtQuantidade.setText(null);
        txtFornNome.setText(null);
        txtFornCod.setText(null);
        txtCod.setText(null);
    }
    
    private void recuperarCod (){
        String sql = "select max(prod_cod) from produto";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()){
                txtCod.setText(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        txtFornCod = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFornNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValidade = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(144, 180, 90));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("*Fornecedor Codigo");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 160, 32);

        jLabel2.setBackground(new java.awt.Color(255, 153, 51));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("*Produto");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 110, 80, 32);

        jLabel3.setBackground(new java.awt.Color(255, 153, 51));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Nota");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 250, 36, 32);

        txtNota.setBackground(new java.awt.Color(144, 180, 90));
        txtNota.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtNota.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNota);
        txtNota.setBounds(210, 240, 430, 50);

        jLabel4.setBackground(new java.awt.Color(255, 153, 51));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("*Quantidade");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 110, 100, 32);

        txtQuantidade.setBackground(new java.awt.Color(144, 180, 90));
        txtQuantidade.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtQuantidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        jPanel1.add(txtQuantidade);
        txtQuantidade.setBounds(500, 120, 137, 20);

        txtFornCod.setBackground(new java.awt.Color(144, 180, 90));
        txtFornCod.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtFornCod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtFornCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornCodActionPerformed(evt);
            }
        });
        txtFornCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFornCodKeyReleased(evt);
            }
        });
        jPanel1.add(txtFornCod);
        txtFornCod.setBounds(210, 40, 137, 20);

        txtProduto.setBackground(new java.awt.Color(144, 180, 90));
        txtProduto.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(txtProduto);
        txtProduto.setBounds(210, 120, 137, 20);

        jLabel5.setBackground(new java.awt.Color(255, 153, 51));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("*Fornecedor Nome");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 70, 160, 32);

        txtFornNome.setBackground(new java.awt.Color(144, 180, 90));
        txtFornNome.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtFornNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtFornNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtFornNome);
        txtFornNome.setBounds(210, 80, 137, 20);

        jLabel6.setBackground(new java.awt.Color(255, 153, 51));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("*Preço");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 150, 80, 32);

        txtPreco.setBackground(new java.awt.Color(144, 180, 90));
        txtPreco.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtPreco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPreco);
        txtPreco.setBounds(210, 160, 137, 20);

        jLabel7.setBackground(new java.awt.Color(255, 153, 51));
        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("*Validade");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(380, 150, 100, 32);

        txtValidade.setBackground(new java.awt.Color(144, 180, 90));
        txtValidade.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtValidade.setText("YYYY/MM/DD");
        txtValidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValidadeActionPerformed(evt);
            }
        });
        jPanel1.add(txtValidade);
        txtValidade.setBounds(500, 160, 137, 20);

        txtCod.setBackground(new java.awt.Color(144, 180, 90));
        txtCod.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtCod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        jPanel1.add(txtCod);
        txtCod.setBounds(210, 190, 137, 20);

        jLabel8.setBackground(new java.awt.Color(255, 153, 51));
        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Codigo");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 180, 80, 32);

        btnSubmit.setBackground(new java.awt.Color(144, 180, 90));
        btnSubmit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSubmit.setText("Submeter");
        btnSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnSubmit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(350, 310, 90, 44);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtFornCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornCodActionPerformed

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void txtFornNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornNomeActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValidadeActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void txtFornCodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFornCodKeyReleased
        // TODO add your handling code here:
        PesquisaFornecedor();
    }//GEN-LAST:event_txtFornCodKeyReleased

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        AdicionarProduto();
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtFornCod;
    private javax.swing.JTextField txtFornNome;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValidade;
    // End of variables declaration//GEN-END:variables
}
