/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Operacao;

/**
 *
 * @author Angel Banze
 */
public class VendaNova extends javax.swing.JInternalFrame {

    /**
     * Creates new form VendaNova
     */
    public VendaNova() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        comboOperador = new javax.swing.JComboBox<>();
        txtNota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProduto1 = new javax.swing.JTextField();
        txtProduto2 = new javax.swing.JTextField();
        txtProduto3 = new javax.swing.JTextField();
        txtProduto4 = new javax.swing.JTextField();
        txtProduto5 = new javax.swing.JTextField();
        btnConcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPreco1 = new javax.swing.JTextField();
        txtPreco2 = new javax.swing.JTextField();
        txtPreco3 = new javax.swing.JTextField();
        txtPreco5 = new javax.swing.JTextField();
        txtPreco4 = new javax.swing.JTextField();
        txtPrecoTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQuantidade1 = new javax.swing.JTextField();
        txtQuantidade2 = new javax.swing.JTextField();
        txtQuantidade3 = new javax.swing.JTextField();
        txtQuantidade4 = new javax.swing.JTextField();
        txtQuantidade5 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(144, 180, 90));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Cliente");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 70, 62, 32);

        jLabel2.setBackground(new java.awt.Color(255, 153, 51));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Operador");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 110, 74, 32);

        jLabel3.setBackground(new java.awt.Color(255, 153, 51));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Nota");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 160, 36, 32);

        comboCliente.setBackground(new java.awt.Color(144, 180, 90));
        comboCliente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        comboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        comboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClienteActionPerformed(evt);
            }
        });
        jPanel1.add(comboCliente);
        comboCliente.setBounds(120, 80, 137, 26);

        comboOperador.setBackground(new java.awt.Color(144, 180, 90));
        comboOperador.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        comboOperador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboOperador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        comboOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOperadorActionPerformed(evt);
            }
        });
        jPanel1.add(comboOperador);
        comboOperador.setBounds(120, 120, 137, 26);

        txtNota.setBackground(new java.awt.Color(144, 180, 90));
        txtNota.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtNota.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtNota);
        txtNota.setBounds(120, 170, 137, 20);

        jLabel4.setBackground(new java.awt.Color(255, 153, 51));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Producto");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 70, 71, 32);

        jLabel5.setBackground(new java.awt.Color(255, 153, 51));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Quantidade");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 70, 89, 32);

        txtProduto1.setBackground(new java.awt.Color(144, 180, 90));
        txtProduto1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtProduto1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtProduto1);
        txtProduto1.setBounds(370, 120, 142, 20);

        txtProduto2.setBackground(new java.awt.Color(144, 180, 90));
        txtProduto2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtProduto2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtProduto2);
        txtProduto2.setBounds(370, 150, 142, 20);

        txtProduto3.setBackground(new java.awt.Color(144, 180, 90));
        txtProduto3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtProduto3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtProduto3);
        txtProduto3.setBounds(370, 180, 142, 20);

        txtProduto4.setBackground(new java.awt.Color(144, 180, 90));
        txtProduto4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtProduto4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtProduto4);
        txtProduto4.setBounds(370, 210, 142, 20);

        txtProduto5.setBackground(new java.awt.Color(144, 180, 90));
        txtProduto5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtProduto5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtProduto5);
        txtProduto5.setBounds(370, 240, 142, 20);

        btnConcluir.setBackground(new java.awt.Color(144, 180, 90));
        btnConcluir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnConcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Actualizar.png"))); // NOI18N
        btnConcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnConcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnConcluir);
        btnConcluir.setBounds(110, 410, 70, 70);

        btnCancelar.setBackground(new java.awt.Color(144, 180, 90));
        btnCancelar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/X.png"))); // NOI18N
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(320, 410, 70, 70);

        btnVoltar.setBackground(new java.awt.Color(144, 180, 90));
        btnVoltar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnVoltar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(510, 430, 70, 44);

        btnImprimir.setBackground(new java.awt.Color(144, 180, 90));
        btnImprimir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/Print.png"))); // NOI18N
        btnImprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnImprimir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnImprimir);
        btnImprimir.setBounds(700, 410, 70, 70);

        jLabel6.setBackground(new java.awt.Color(255, 153, 51));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Preço");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(760, 70, 44, 32);

        txtPreco1.setBackground(new java.awt.Color(144, 180, 90));
        txtPreco1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtPreco1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtPreco1);
        txtPreco1.setBounds(760, 120, 53, 20);

        txtPreco2.setBackground(new java.awt.Color(144, 180, 90));
        txtPreco2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtPreco2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtPreco2);
        txtPreco2.setBounds(760, 150, 53, 20);

        txtPreco3.setBackground(new java.awt.Color(144, 180, 90));
        txtPreco3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtPreco3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtPreco3);
        txtPreco3.setBounds(760, 180, 53, 20);

        txtPreco5.setBackground(new java.awt.Color(144, 180, 90));
        txtPreco5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtPreco5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtPreco5);
        txtPreco5.setBounds(760, 240, 53, 20);

        txtPreco4.setBackground(new java.awt.Color(144, 180, 90));
        txtPreco4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtPreco4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtPreco4);
        txtPreco4.setBounds(760, 210, 53, 20);

        txtPrecoTotal.setBackground(new java.awt.Color(144, 180, 90));
        txtPrecoTotal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtPrecoTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtPrecoTotal);
        txtPrecoTotal.setBounds(760, 290, 53, 20);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Total");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(650, 290, 39, 18);

        txtQuantidade1.setBackground(new java.awt.Color(144, 180, 90));
        txtQuantidade1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtQuantidade1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtQuantidade1);
        txtQuantidade1.setBounds(570, 120, 142, 20);

        txtQuantidade2.setBackground(new java.awt.Color(144, 180, 90));
        txtQuantidade2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtQuantidade2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtQuantidade2);
        txtQuantidade2.setBounds(570, 150, 142, 20);

        txtQuantidade3.setBackground(new java.awt.Color(144, 180, 90));
        txtQuantidade3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtQuantidade3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtQuantidade3);
        txtQuantidade3.setBounds(570, 180, 142, 20);

        txtQuantidade4.setBackground(new java.awt.Color(144, 180, 90));
        txtQuantidade4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtQuantidade4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtQuantidade4);
        txtQuantidade4.setBounds(570, 210, 142, 20);

        txtQuantidade5.setBackground(new java.awt.Color(144, 180, 90));
        txtQuantidade5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtQuantidade5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(txtQuantidade5);
        txtQuantidade5.setBounds(570, 240, 142, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClienteActionPerformed

    }//GEN-LAST:event_comboClienteActionPerformed

    private void comboOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOperadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOperadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JComboBox<String> comboOperador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtPreco1;
    private javax.swing.JTextField txtPreco2;
    private javax.swing.JTextField txtPreco3;
    private javax.swing.JTextField txtPreco4;
    private javax.swing.JTextField txtPreco5;
    private javax.swing.JTextField txtPrecoTotal;
    private javax.swing.JTextField txtProduto1;
    private javax.swing.JTextField txtProduto2;
    private javax.swing.JTextField txtProduto3;
    private javax.swing.JTextField txtProduto4;
    private javax.swing.JTextField txtProduto5;
    private javax.swing.JTextField txtQuantidade1;
    private javax.swing.JTextField txtQuantidade2;
    private javax.swing.JTextField txtQuantidade3;
    private javax.swing.JTextField txtQuantidade4;
    private javax.swing.JTextField txtQuantidade5;
    // End of variables declaration//GEN-END:variables
}
